inherit_from: rubocop-todo.yml

AllCops:
  Includes: 
    - Rakefile
    - config.ru
  Excludes:
    - bin/**
    - config/**
    - db/**
    - node_modules/**
    - script/**
    - vendor/**
  RunRailsCops: true
