inherit_from: rubocop-todo.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**
    - config/**
    - db/**
    - features/support/upload_from_garmin.rb
    - spec/support/uploaded_activity.rb
    - node_modules/**
    - script/**
    - vendor/**
  RunRailsCops: true
