inherit_from: rubocop-todo.yml

AllCops:
  Includes: 
    - Rakefile
    - config.ru
  Excludes:
    - bin/**
    - config/**
    - db/**
    - features/support/upload_from_garmin.rb
    - node_modules/**
    - script/**
    - vendor/**
  RunRailsCops: true
