#!/bin/sh

function check_version {
  $1

  if [ $? -ne 0 ]; then
    exit 1;
  fi
}

check_version "git --version"
check_version "ruby -v"
check_version "gem -v"
check_version "bundle -v"
check_version "psql --version"
check_version "phantomjs --version"
check_version "npm -v"
check_version "qmake -v"

bundle
bundle binstubs rspec-core --force
bundle binstubs cucumber --force
bundle binstubs rails_best_practices --force
bundle binstubs consistency_fail --force
bundle binstubs teaspoon --force
bundle binstubs rubocop --force
npm install

cp -n .env.example .env
cp -n config/database.yml.example config/database.yml

rake db:create
