#!/bin/sh

function clean_assets_and_exit {
  rm -r public/assets
  exit $1
}

function run_command {
  $1

  if [ $? -ne 0 ]; then
    clean_assets_and_exit 1
  fi
}

script/bootstrap

# start xvfb if required
# export DISPLAY=${DISPLAY:-":2.0"}
# ps x | grep -v grep | grep Xvfb || nohup Xvfb -ac -screen scrn 1400x900x24 "$DISPLAY" &

run_command "rm -rf coverage/*"

rake db:migrate
rake assets:precompile

run_command "bin/consistency_fail"
run_command "bin/teaspoon"
run_command "rake spec"
run_command "rake cucumber"
run_command "script/huxley test"
run_command "rake quality"
run_command "bin/rails_best_practices ."

clean_assets_and_exit 0
