#!/bin/sh


heroku pgbackups:capture --app aerobic
curl -o latest.dump `heroku pgbackups:url --app aerobic`
pg_restore --verbose --clean --no-acl --no-owner -h localhost -d aerobicio_development latest.dump
rm latest.dump
