#!/bin/bash +xe

HUXLEY_SERVER_PORT=8899
HUXLEY_SERVER_PID_PATH=tmp/pids/unicorn.pid
HUXLEY_EXIT_CODE=0
LOG_DIR=log

function start_app_server {
  # Start unicorns via nohup and hold onto unicorn master pid.
  touch $HUXLEY_SERVER_PID_PATH
  nohup bundle exec unicorn -p $HUXLEY_SERVER_PORT &
  echo $! > $HUXLEY_SERVER_PID_PATH
  while ! nc -vw 1 localhost $HUXLEY_SERVER_PORT; do sleep 1; done
}

function teardown {
  # Clean up dead unicorns.
  if [[ -f $HUXLEY_SERVER_PID_PATH ]]; then
    kill -QUIT `cat $HUXLEY_SERVER_PID_PATH`
    rm $HUXLEY_SERVER_PID_PATH
  fi
}

function huxley_test {
  start_app_server
  huxley --playback-only --save-diff -f ./spec/ui/**Huxleyfile
  HUXLEY_EXIT_CODE=$?
  teardown
  exit $HUXLEY_EXIT_CODE
}

function huxley_record {
  # first run through is used to record interactions and steps using a visual
  # browser (firefox)
  start_app_server
  huxley -f ./spec/ui/**Huxleyfile
  HUXLEY_EXIT_CODE=$?
  teardown
  exit $HUXLEY_EXIT_CODE
}

case "$1" in
  test)
    echo -n "Run Huxley tests and check for UI regressions."
    huxley_test
    ;;
  record)
    echo -n "Recording Huxley tests"
    huxley_record
    ;;
  *)
  echo "Usage: huxley {test|record|reprocess}"
  exit 1
esac
